### ISSUE TITLE
Add a way to specify you want only https urls from metalink

### ISSUE THREAD

**Issue by nirik** [fedora-infra/mirrormanager2#100]
Some folks want all their traffic to use ssl, we should offer a option to the metalink url that makes it return just https using mirrors. Something like ?method=https or the like in the url. 

Along with this we might consider mailing mirror admins and asking if they would update to https where they have https available. 

Once enough mirrors offered https we could make it the default perhaps.

**Comment by adrianreber** [comment]
This is now running on the Fedora production systems.

**Comment by mdomsch** [comment]
Glad to see this, but the whole point of metalinks is to let the clients
decide what they want to use - give them all the possible URLs and then
they choose what they want. This properly belongs in a dnf configuration,
not MM2. As it stands, the user now has to change the dnf configuration
anyhow, to add the specifier on the metalink URL.

**Comment by adrianreber** [comment]
Yes, I agree with @mdomsch. The official way to make metalink clients use HTTPS must be different. This needs some additional work on other parts (could be dnf). At least there is now a way for people who want to use it and we also know that it works and it is a starting point. It was also a good way to get more HTTPS URLs in the database. But, yes, now that more HTTPS URLs are in the database an option to make dnf prefer HTTPS URLs if available in the metalink sounds like a good idea.

**Comment by nirik** [comment]
Sure, that makes some sense... I can ask dnf / librepo maintainers about options there.

**Comment by nirik** [comment]
And there is already https://bugzilla.redhat.com/show_bug.cgi?id=1229050 (dnf should provide a protocol option) and https://bugzilla.redhat.com/show_bug.cgi?id=1273051 (librepo should provide a supported protocol list).
