### ISSUE TITLE
Sort repomd.xml by time in metalink

### ISSUE THREAD

**Issue by nirik** [fedora-infra/mirrormanager2#116]
It would help consumers of our metalink if the repomd.xml's are sorted by time, with the newest one at the top and the alternates being older in turn. 

See discussion in https://fedorahosted.org/fedora-infrastructure/ticket/4866

**Comment by adrianreber** [comment]
This has been implemented in #121 and will be available with the next release.

**Comment by adrianreber** [comment]
This change is now running in production.
