### ISSUE TITLE
Heading missing in mirror overview

### ISSUE THREAD

**Issue by adrianreber** [fedora-infra/mirrormanager2#133]
There is currently no heading in the mirror overview at:

https://admin.fedoraproject.org/mirrormanager/mirrors

Especially the Yes/No for "Internet2" enabled is hard to guess.

**Comment by pypingou** [comment]
Indeed

**Comment by pypingou** [comment]
Fixed by https://github.com/fedora-infra/mirrormanager2/pull/136
