### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by Conan-Kudo** [fedora-infra/mirrormanager2#139]
With [Fedora working hard to have Python 3 as the default](https://fedoraproject.org/wiki/Changes/Python_3_as_Default), and [EPEL now including python34 for EL7](https://dl.fedoraproject.org/pub/epel/7/x86_64/repoview/python34.html) (and of course, there's Software Collections for Python 3.4 for EL6 and EL7), it would be awesome if MirrorManager2 added Python 3 support.

A cursory check at the requirements files in the repository indicate that there are only four modules that don't indicate Python 3 support in PyPi:
- python-fedora
- python-openid
- python-openid-cla
- python-openid-teams

I don't know to what extent these modules are required, but perhaps a first step would be to make MirrorManager2 itself Py3 ready with the six module? If the modules above aren't mandatory to MirrorManager2's functionality, then perhaps splitting the stuff that uses that out as a subpackage to make the core available with Py3 is an option?

**Comment by pypingou** [comment]
Porting to py3 is a nice idea, but do you know any potential users of MM2 in py3?

**Comment by Conan-Kudo** [comment]
@pypingou Yes. Mageia would be a potential user, as I'm currently evaluating how to deploy the mirroring of rpm-md repositories for DNF on Mageia. If it is possible to deploy MirrorManager2 as a Python 3 application, that would make it more attractive, as I don't particularly enjoy the idea of deploying new infrastructure that depends on Python 2 if I can help it.

**Comment by pypingou** [comment]
Roger that, thanks

**Comment by ralphbean** [comment]
FYI, all of those deps are all py3-ready now.  All that is left is to port MM2 itself.

**Comment by keszybz** [comment]
This can be closed now. If any python3 issues appear, they should probably be tracked separately.

**Comment by adrianreber** [comment]
@keszybz thanks
