### ISSUE TITLE
Admin_active was disabled on a newly created host

### ISSUE THREAD

**Issue by adrianreber** [fedora-infra/mirrormanager2#141]
I have seen that on a newly created host (by a non admin user) the admin_active flag was not set. The site was behaving correctly but not the host.

**Comment by pypingou** [comment]
I just tried to replicate this locally, but ``admin_active`` is true for both the host and the site.

Can you reproduce it on a local instance?

**Comment by pypingou** [comment]
oh, that's because it has been fixed in https://github.com/fedora-infra/mirrormanager2/pull/132

We just don't have a release with this yet.

Anyway, let's close this for now.
