### ISSUE TITLE
Text for "Master rsync server Access Control List IPs" misleading

### ISSUE THREAD

**Issue by adrianreber** [fedora-infra/mirrormanager2#145]
Each host has the possibility to define "Master rsync server Access Control List IPs" which has following description:

> These host DNS names and/or IP addresses will be allowed to rsync from the master rsync/ftp servers. List here all the machines that you use for pulling.

This is not true. Access to the master mirror in Fedora is not granted automatically. Maybe we should hide this part for Fedora's MirrorManager installation. There used to be a way for mirrors to query all hosts listed in this field via /rsync_acls/ to populate the "hosts allow" field of the local rsync daemon. This does not exist in MirrorManager2 any more as it never had many users.

So we could remove this functionality at least from the Fedora templates.

**Comment by srisankethu** [comment]
@ralphbean Is this done? Or can I make changes?

**Comment by adrianreber** [comment]
@srisankethu This issue is still open.

**Comment by adrianreber** [comment]
See #200
