### ISSUE TITLE
Simpler checkin endpoint(s)

### ISSUE THREAD

**Issue by jasontibbitts** [fedora-infra/mirrormanager2#170]
I would like to be able to do a checkin from a shell script.  I know the current checkin xmlrpc checkin endpoint is there for compatibility with existing report_mirror checkins, but it would be nice to have something that's a bit simpler to use.

I propose to add two API endpoints to api.py:  checkin-json and checkin-text.  These will take json or a text file and parse that into a structure suitable for passing to read_host_config.  Compressed endpoints could be added, too.  The json should be trivial to generate from the regular report_mirror data structure that gets pickled.  The text file should be easy to generate from a shell script.

Given the fact that you should really shouldn't unpickle untrusted data, I'd figure that this would be something you wouldn't mind adding.  I think that doing this should be pretty easy for me, but I'm not sure how I'm going to test it.  Any hints as to how you'd want to see this done would be appreciated, of course.

**Comment by adrianreber** [comment]
The new interfaces you propose sound reasonable. Not entirely sure what to expect from checkin-text. Compressing the transmitted data would be nice I think.

Testing it can be done using the staging instance I would say.

**Comment by jasontibbitts** [comment]
So puiterwijk add a json checkin mechanism to the regular checkin endpoint as part of getting rid of the unpickle operation.  He also indicated that he would go ahead an add a regular json submission endpoint that doesn't involve dealing with xmlrpc.  (And also add a way to send gzipped data instead of requiring bzip2.)  So I'm going to see if it's workable to just generate the json directly in the quick-fedora-mirror shell script and go with that.  If not, then I'll work on some format.

**Comment by adrianreber** [comment]
I guess this is resolved with #173

**Comment by jasontibbitts** [comment]
Not 100%, since puiterwijk was going to add a regular, non-xmlrpc endpoint for me to use.  I can follow up with him on that.
