### ISSUE TITLE
Mirrors with only a HTTPS URL cannot be crawled

### ISSUE THREAD

**Issue by adrianreber** [fedora-infra/mirrormanager2#183]
The function method_pref() in the crawler cannot correctly handle mirrors which only provide a HTTPS URL. The simplest fix would probably be to remove the ':' in `u.startswith('http:')`.

**Comment by haydenjames** [comment]
Avoid adding https and use http instead? Or fixed?

**Comment by adrianreber** [comment]
At least one HTTP or RSYNC URL needs to be available. If that is the case HTTPS can be added.

**Comment by adrianreber** [comment]
Fixed by #192
