### ISSUE TITLE
Only admins should be able to change "Always up to date"

### ISSUE THREAD

**Issue by adrianreber** [fedora-infra/mirrormanager2#186]
The checkbox "Always up to date" in the "host category" should only be available for admins so that it is not accidentally selected like:

https://fedorahosted.org/fedora-infrastructure/ticket/5454

**Comment by pypingou** [comment]
It seems it is already only shown to admins: https://github.com/fedora-infra/mirrormanager2/blob/master/mirrormanager2/templates/fedora/host_category_new.html#L23

**Comment by adrianreber** [comment]
Even better. Then the flag (in the referenced fedora-infrastructure ticket)  must have been set when it was still available to every user.

**Comment by pypingou** [comment]
Checked locally and the settings is also not available when adding or editing the cateogory of a host.
