### ISSUE TITLE
Filtering arches from repo creation

### ISSUE THREAD

**Issue by nirik** [fedora-infra/mirrormanager2#210]
This is a upstream tracker for 
https://pagure.io/fedora-infrastructure/issue/5186

basically we need a way to tell mirrormanager that some arches are available only in archives and shouldn't be listed for anything newer when making repositories. 

See downstream issue for more info...

**Comment by adrianreber** [comment]
Kind of fixed. With PR #223 the arches are filtered out from the overview if marked as 'publiclist=false' in the database. The arches are not actually filtered out from the repository creation but removing certain arches from there was what actually was requested in the original ticket.
