### ISSUE TITLE
/usr/bin/mm2_get_internet2_netblocks no longer works

### ISSUE THREAD

**Issue by nirik** [fedora-infra/mirrormanager2#226]
It seems the site this script was pulling netblocks from is no longer valid. 

The script outputs: 

gzip: /tmp/get_i2_netblocks.YcUbPEXF/rib.gz: unexpected end of file
short file (empty packet) at zebra-dump-parser/zebra-dump-parser.pl line 98.

gzip: /tmp/get_i2_netblocks.YcUbPEXF/rib.gz: unexpected end of file
short file (empty packet) at zebra-dump-parser/zebra-dump-parser.pl line 98.

gzip: /tmp/get_i2_netblocks.YcUbPEXF/rib.gz: unexpected end of file
short file (empty packet) at zebra-dump-parser/zebra-dump-parser.pl line 98.

gzip: /tmp/get_i2_netblocks.YcUbPEXF/rib.gz: unexpected end of file
short file (empty packet) at zebra-dump-parser/zebra-dump-parser.pl line 98.

gzip: /tmp/get_i2_netblocks.YcUbPEXF/rib.gz: unexpected end of file
short file (empty packet) at zebra-dump-parser/zebra-dump-parser.pl line 98.

gzip: /tmp/get_i2_netblocks.YcUbPEXF/rib.gz: unexpected end of file
short file (empty packet) at zebra-dump-parser/zebra-dump-parser.pl line 98.

gzip: /tmp/get_i2_netblocks.YcUbPEXF/rib.gz: unexpected end of file
short file (empty packet) at zebra-dump-parser/zebra-dump-parser.pl line 98.

gzip: /tmp/get_i2_netblocks.YcUbPEXF/rib.gz: unexpected end of file
short file (empty packet) at zebra-dump-parser/zebra-dump-parser.pl line 98.

gzip: /tmp/get_i2_netblocks.YcUbPEXF/rib.gz: unexpected end of file
short file (empty packet) at zebra-dump-parser/zebra-dump-parser.pl line 98.
unable to retrieve netblock list.

http://zebra.net.internet2.edu/bgp no longer has this information. We need to find out where it moved to if anywhere.

**Comment by mdomsch** [comment]
You may need to open a support ticket with the Internet2 NOC and ask them
what happened to this server, and if there's a replacement.
It may be https://routerproxy.grnoc.iu.edu/internet2/ somehow.  There's at
least a link there to the NOC.

**Comment by adrianreber** [comment]
I submitted a ticket. The ticket number is 17605 but it seems it is not accessible: ```You do not have permission to view ticket 17605``` : https://tick.globalnoc.iu.edu/fp_tools/public_ticket_viewer/index.cgi?method=view_ticket&tick=17605&proj=144

**Comment by adrianreber** [comment]
After opening a ticket they were very helpful and said they just forgot about it. The service is now available at: https://routes.net.internet2.edu/bgp/

The format might have changed, but the data is available again. I will have a look at adopting our scripts.

**Comment by adrianreber** [comment]
Fixed.
