### ISSUE TITLE
Please use "site", "host" and "mirror" consistently

### ISSUE THREAD

**Issue by jasontibbitts** [fedora-infra/mirrormanager2#238]
I received a complaint that quick-fedora-mirror wasn't clear in its documentation of the variables regarding doing mirrormanager checkins, so I had a look at mirrormanager to see exactly what it calls various things.  Unfortunately it's not consistent.

When you look at the "My Sites" page, you get a list of "sites" and grouped together the list of "mirrors" beneath those.

When you click on one of those sites, you get a form with "Site name", "Site Password", etc. and a list of "hosts" (not mirrors) below.

If you click on a host/mirror from either of those pages, you get to a form which has "Site name" again, but this isn't the same "Site name" from the site page.

So changing to "Host name" on the host page would make sense, as well as using the word "host" instead of "mirror" on the "My Sites" page (though that's more minor).

**Comment by adrianreber** [comment]
Fixed in #241
