### ISSUE TITLE
GeoIP legacy is EOL

### ISSUE THREAD

**Issue by smooge** [fedora-infra/mirrormanager2#248]
https://support.maxmind.com/geolite-legacy-discontinuation-notice/

Our GeoLite Legacy databases are being discontinued
 

We have decided to discontinue our GeoLite Legacy databases effective January 2, 2019. We will stop updating the databases before that date (see “General Information” below), and the databases will no longer be available for download on January 2, 2019. This was a difficult decision for us and we have created this page to provide more information and answer any immediate questions you may have.

===============
It looks like they are freezing updates to the geolite-legacy so we will need to use the geolite2 or geoip2 library calls.

**Comment by adrianreber** [comment]
Thanks, I had a look over the code and it should not be too difficult to change it. Currently support for GeoIP is in the crawler, mirrorlist and mm2_generate-worldmap.

The crawler does not really use it but all those occurrences should be easy to convert to the new API.
