### ISSUE TITLE
yum 3 will be deprecated in Fedora 29

### ISSUE THREAD

**Issue by adrianreber** [fedora-infra/mirrormanager2#251]
According to https://pagure.io/releng/issue/7588 yum 3 will be deprecated in Fedora 29.

Mirrormanager currently does at least in four files:

```import yum.repoMDObject```

Need to figure out if this still works with DNF.

**Comment by Conan-Kudo** [comment]
This does not work in DNF. There is `python-pyrpmmd` which provides that exact API for Python 2 and Python 3.

Alternatively, you can use librepo's Python bindings.

**Comment by adrianreber** [comment]
@Conan-Kudo thanks for the pointers, good to know
