### ISSUE TITLE
weird release numbers on https://admin.fedoraproject.org/mirrormanager/

### ISSUE THREAD

**Issue by cheese1** [fedora-infra/mirrormanager2#263]
there are weird release-numbers in the list
besides the list is not very readable.

**Comment by cheese1** [comment]
![screenshot from 2019-02-17 15-06-38](https://user-images.githubusercontent.com/6437726/52914179-aa61e800-32c5-11e9-8242-79d90cd02f99.png)

**Comment by adrianreber** [comment]
Thanks for the report. This happens sometimes that the version auto-detect logic triggers on path it should ignore.

I fixed it in the database and I guess I should introduce a setting with which it is possible to ignore certain paths during version detection.

All those number are from the `alt` directory tree which is something that basically should never trigger a version in the mirrorlist. Also Beta and Alpha should be excluded.

**Comment by cheese1** [comment]
upps
i did it again :)
the "weird" numbers are back again

**Comment by cheese1** [comment]
and now they are gone again, thanks

**Comment by adrianreber** [comment]
I did not actually fix this, I just marked them as display='f'. But I should really fix this.
