### ISSUE TITLE
Private Mirror in Public Site not able to check in

### ISSUE THREAD

**Issue by survient** [fedora-infra/mirrormanager2#286]
In a review of one of our private mirrors we have found that it has been throwing the error "Only private mirrors are allowed to use report_mirror" despite being marked as Private Host in Mirror Manager.

Doing some digging I found the following commit:
https://github.com/fedora-infra/mirrormanager2/commit/e63d9dfbe2b1544f85d2ef4ac3584cd10cda5a7c
Where a mirror apparently has to be both marked as a Private Host *within* a Private Site. I'm raising this issue as I think a Private Host should be allowed to check-in  even if it lives in a Public Site. We host Fedora content on the same back-end for both our private and public mirrors however route access differently depending on the domain name used which if configured correctly allows our office repo-related traffic to route more efficiently. Since it's on the same infrastructure it makes more sense for it to be part of the same site, beyond the fact that from this change the "Private" option on a host is selectable while living in a Public Site is made redundant and non-functional.

**Comment by adrianreber** [comment]
Makes sense. Will fix it in the next release.
