### ISSUE TITLE
Last Checked In shows stale timestamp on Public Hosts

### ISSUE THREAD

**Issue by survient** [fedora-infra/mirrormanager2#287]
Since https://github.com/fedora-infra/mirrormanager2/commit/e63d9dfbe2b1544f85d2ef4ac3584cd10cda5a7c the "Last Checked In" field under a Public Hosts' properties shows a stale timestamp when from that commit's point forward the intent was for Public Hosts to no longer use report_mirror. On Public Hosts this field should either be hidden or show an appropriate value when "Private" is unchecked. Otherwise mirror owners may become confused(as I did) when seeing a recent "Last Crawled" but a stale "Last Checked In". I suppose the same logic could be applied in reverse for Private Hosts with the "Last Crawled" field.

**Comment by adrianreber** [comment]
Also a good idea. Thanks. Will fix it in the next release.
