### ISSUE TITLE
Let MirrorManager2 authenticate using OpenID Connect

### ISSUE THREAD

**Issue by nphilipp** [fedora-infra/mirrormanager2#289]
Currently, MirrorManager2 uses OpenID to authenticate users via Ipsilon(⇒FAS), implement OpenID Connect authentication because that's what works with ipsilon ⇒ IPA.

**Comment by nphilipp** [comment]
Hmm, apparently we'll support plain OpenID with ipsilon ⇒ IPA still. Closing.

**Comment by ryanlerch** [comment]
Going to reopen this one now.

While the new Fedora Accounts / Ipsilon / Noggin / FreeIPA does support OpenID, we are trying to get everything over to OIDC.

**Comment by Zlopez** [comment]
This should be now solved by https://github.com/fedora-infra/mirrormanager2/pull/301
