### ISSUE TITLE
How to add category and some other items

### ISSUE THREAD

**Issue by awsome0305** [fedora-infra/mirrormanager2#299]
Hi,

I found that the web front of mirrormanager cannot add category and some other items,is there any other ways to add them?Or do I have to manipulate the database to add them?

**Comment by adrianreber** [comment]
Yes, that needs to be done directly in the database. It does not happen often enough that no one wrote a tool to add a category.

**Comment by adrianreber** [comment]
Did you try the admin view? I am adding new categories always directly in the database, but there is the admin view which should allow adding categories.

**Comment by awsome0305** [comment]
Yes, I tried to use the admin view.But there was no any function.It looks like I have to directly modify the database.

Thank you very much.

**Comment by James6xie** [comment]
> Did you try the admin view? I am adding new categories always directly in the database, but there is the admin view which should allow adding categories.

HI man , is there any scripts to add categories by DB?  admin view had nothing for me .

**Comment by adrianreber** [comment]
> > Did you try the admin view? I am adding new categories always directly in the database, but there is the admin view which should allow adding categories.
> 
> HI man , is there any scripts to add categories by DB?

No, it is a manual process currently. No one has written a script yet.

> admin view had nothing for me .

You should be able to create new category in the admin view. Never used myself, but I see it exists. I just do a `INSERT INTO...`.
