### ISSUE TITLE
JSON export with latest mirror update date

### ISSUE THREAD

**Issue by abitrolly** [fedora-infra/mirrormanager2#313]
Could not find any official API at https://mirrormanager.readthedocs.io/en/latest/ so it might be that the method that exports JSON data already exists. In any case it would be nice to have API documented.

I want to find the mirror that already contains the update FEDORA-2022-8cf9d64c36 pushed yesterday. I tried several with no luck. The website provides information that some mirrors are out of sync, but doesn't specify which are uptodate. With JSON data export I can quickly grep and sort to find this out.

**Comment by adrianreber** [comment]
There is no such API. If you can figure out the checksum of the repomd.xml that contains FEDORA-2022-8cf9d64c36 then it should be doable to get a list of mirrors that contains this update, but MirrorManager has no knowledge about things like  FEDORA-2022-8cf9d64c36. MirrorManager only tracks the checksums of repomd.xml files.

I am closing this as we do not have any knowledge on the MirrorManager level about the content and labels like  FEDORA-2022-8cf9d64c36. This is only about checksums.

**Comment by abitrolly** [comment]
@adrianreber can I get the JSON of everything that MirrorManager knows about repos? Time of the last update should cover it.

**Comment by adrianreber** [comment]
Each metalink contains a timestamp and checksum for each repository/architecture combination. Not JSON but XML.

**Comment by abitrolly** [comment]
Where to find these metalinks? I don't see them here https://admin.fedoraproject.org/mirrormanager/ to see how can I parse them.

**Comment by adrianreber** [comment]
Just have a look in your repository definition files in `/etc/yum.repos.d/`. Something like:

https://mirrors.fedoraproject.org/metalink?repo=fedora-36&arch=x86_64

**Comment by abitrolly** [comment]
So I need to go over these files one by one. Does `mirrormanager2` parse them already?
