### ISSUE TITLE
hkg.mirror.rackspace.com mirror is never in the mirror list

### ISSUE THREAD

**Issue by proletarius101** [fedora-infra/mirrormanager2#314]
`https://hkg.mirror.rackspace.com/fedora` is listed in https://admin.fedoraproject.org/mirrormanager/mirrors/Fedora/36/x86_64, but it's not in the list of `https://mirrors.fedoraproject.org/metalink?repo=fedora-36&arch=x86_64&country=hk`

**Comment by adrianreber** [comment]
Closing this as GitHub is used for the development of MirrorManager. Problems with mirrors for the Fedora instance of MirrorManager should be reported at: https://pagure.io/fedora-infrastructure/issues.

I had a look at the mirror and it is not up to date, that is why it is not listed in the metalink. The metalink knows about each architecture and each version of Fedora.

The mirror overview page does not know these details and gives an overview about which mirrors exist but should never be used to determine if a mirror is up to date or not. Only the metalink has this information.
