### ISSUE TITLE
Fedora updates with dnf consistently chooses very slow mirrors form asian regions.

### ISSUE THREAD

**Issue by AlawamiAZ** [fedora-infra/mirrormanager2#319]
Not sure if this is the right place or it belong to dnf..

Fedora behavior of choosing mirror for updates consistently chooses the worst mirrors for me. I'm from saudi arabia and while my connections to EU and NA is  usually around 300mbps, my connection to most  countries is around <30mbps  (usually 10mbps) yet fedora consistently chooses mirrors from japan and china which are very slow for me. 

Is it choosing mirrors based on continent? because that's resulting in very poor bandwidth.

This not only happens with dnf but even downloading ISOs form fedoraproject.org also always gives me asian mirrors.

**Comment by adrianreber** [comment]
This is indeed not the right place for the Fedora instance of MirrorManager.

https://pagure.io/fedora-infrastructure/ would be the right place.

The way MirrorManager selects the mirror is first by country and then by continent. If there are no up to date mirrors in your country then you will be redirected to mirrors on your continent as defined by maxmind's geo IP database.

There is the possibility to assign a country to another continent but that means that all traffic from your country would be redirected.

But you should bring this up at Fedora's issue tracker and we can decide there if we can do this.

**Comment by adrianreber** [comment]
https://pagure.io/fedora-infrastructure/issue/11347
