### ISSUE TITLE
https://mirrors.centos.org/centos is offline

### ISSUE THREAD

**Issue by grepwood** [fedora-infra/mirrormanager2#322]
Where am I supposed to get CentOS 8-stream from now? Has anyone even considered how many people use this address before disabling it?

**Comment by arrfab** [comment]
nothing was disabled as it has never been available through that url/hostname :)
https://www.centos.org/download/ has the link for stream 8 , pointing to http://mirror.centos.org .. while mirrors.centos.org is indeed pointing to mirrormanager and only starting from stream 9
see also https://www.centos.org/download/mirrors/
