### ISSUE TITLE
Link to https://admin.fedoraproject.org/mirrormanager/

### ISSUE THREAD

**Issue by abitrolly** [fedora-infra/mirrormanager2#334]
It would be nice to link to https://admin.fedoraproject.org/mirrormanager/ from repository description to see `mirrormanager2` in action.

**Comment by adrianreber** [comment]
Sounds like a good idea. Please open a pull request.

**Comment by abitrolly** [comment]
@adrianreber it can not be done with PR. Somebody with admin privileges need to click this.

![image](https://github.com/fedora-infra/mirrormanager2/assets/8781107/0d37b687-72c4-4b30-b8c2-84d522b1a232)

**Comment by abompard** [comment]
Done! :-)
