### ISSUE TITLE
Don't disable mirrors silently

### ISSUE THREAD

**Issue by abompard** [fedora-infra/mirrormanager2#342]
At the moment, mirrors are disabled after a threshold of consecutive crawl failures. This does not cause an email to be sent, or a message to be emitted. Mirrors should not be disabled (or re-enabled) silently.
Mirrormanager could send a Fedora Message that would be sent out as a notification by FMN. The "robot_email" column could also be used to send an email directly.

**Comment by ryanlerch** [comment]
Duplicate of #246
