### ISSUE TITLE
Unable to enable mirror

### ISSUE THREAD

**Issue by jcpunk** [fedora-infra/mirrormanager2#344]
Mirror Manager link: https://mirrormanager.fedoraproject.org/host/2607

Page times out and returns a 502 error.  Fedora Quick Mirror is up to date from HEAD and shows no changes required when running.

https://linux-mirrors.fnal.gov/linux/fedora/epel/ looks right to me
https://linux-mirrors.fnal.gov/linux/centos-stream/ looks right to me

**Comment by abompard** [comment]
Hey @jcpunk , could you please try again? The page opens up fine for me at the moment.

**Comment by jcpunk** [comment]
Mirror seems to be active now. So I'd say I'm probably sorted.
