### ISSUE TITLE
are these valid fedora infra crawler IPs

### ISSUE THREAD

**Issue by bilias** [fedora-infra/mirrormanager2#347]
Hi,
We're seeing thousands of hits on our mirror from 2 IPs.
Are these yours?

```
 Hits      h% Vis.     v% Tx. Amount Data
 ----- ------ ---- ------ ---------- ----
 63566 10.34%    1  0.00%   2.63 MiB 38.145.60.4                             
 24905  4.05%    2  0.00%   1.51 MiB 38.145.60.3                      

38.145.60.3 - - [07/Jun/2024:03:27:10 +0300] "GET /pub/linux/epel/9/Everything/x86_64/repodata/repomd.xml HTTP/1.1" 200 4374 "-" "mirrormanager-crawler/0.1 (+https://github.com/fedora-infra/mirrormanager2/)"
38.145.60.3 - - [07/Jun/2024:08:00:05 +0300] "HEAD /mirrors/linux/centos-stream/9-stream/AppStream/aarch64/os/.discinfo HTTP/1.1" 200 0 "-" "mirrormanager-crawler/0.1 (+https://github.com/fedora-infra/mirrormanager2/)"

38.145.60.4 - - [07/Jun/2024:03:26:59 +0300] "GET /pub/linux/fedora/linux/updates/38/Everything/x86_64/repodata/repomd.xml HTTP/1.1" 404 146 "-" "mirrormanager-crawler/0.1 (+https://github.com/fedora-infra/mirrormanager2/)"
38.145.60.4 - - [07/Jun/2024:03:45:16 +0300] "HEAD /pub/linux/epel/7/aarch64/debug/Packages/c/CUnit-debuginfo-2.1.3-8.el7.aarch64.rpm HTTP/1.1" 200 0 "-" "mirrormanager-crawler/0.1 (+https://github.com/fedora-infra/mirrormanager2/)"
```

Most of them are HEAD requests.
These are too many hits. Is this valid traffic?

**Comment by abompard** [comment]
Hello! Yes, this is the system that Fedora uses to ensure that the mirrors are up-to-date. An alternative would be to open an rsync connection from our IP, which will result in a single rsync connection.

https://fedoraproject.org/wiki/Infrastructure/Mirroring#Rsync_Configuration_(sample)

Would that be an option for you?

**Comment by bilias** [comment]
Hi,
We already run rsync on this mirros, and rsync is also registered in Mirrormanager.

I can't find any option in mirrormanager to apply for rsync mirror checking.

**Comment by abompard** [comment]
I'll check it, could you please indicate what is the mirror name? (or ID, if you don't want to disclose the name)

**Comment by bilias** [comment]
site 128
host 488

**Comment by abompard** [comment]
Hey! Sorry for the delay. I'm currently running a check on this host and it looks like it is using rsync to get the list of files and their sizes. Do you still see these head requests?

**Comment by bilias** [comment]
Sorry for the delay.
I still see head requests from those 2 IPs on my web servers.

I also see rsync access from 38.145.60.3

**Comment by abompard** [comment]
I may have found why: looking at your mirrormanager page it looks like the CentOS category does not have rsync defined as an access method. Could you add it please?

**Comment by bilias** [comment]
Updated centos-stream and added rsync URL

**Comment by abompard** [comment]
Thanks! My tests show that no HEAD requests should be produced now, can you please confirm when the next crawl is done?
There will still be GET requests on the repomd metadata files though, but there's far less of them.

**Comment by bilias** [comment]
seems fine now, thanks

**Comment by bilias** [comment]
> I may have found why: looking at your mirrormanager page it looks like the CentOS category does not have rsync defined as an access method. Could you add it please?

@abompard 
Hi, I've started having the same problem with rpmfusion.
Is that mirrormanager handled by fedora and you guys or not?

Thanks

**Comment by abompard** [comment]
Nope we don't host that instance.
