### ISSUE TITLE
Remove ELN ResilientStorage from mirrors

### ISSUE THREAD

**Issue by yselkowitz** [fedora-infra/mirrormanager2#409]
The ResilientStorage variant of ELN has been disabled; to that end, please remove the following entries from the mirror database:
```
# repo=eln-resilientstorage-1&arch=ppc64le
# repo=eln-resilientstorage-1&arch=s390x
# repo=eln-resilientstorage-1&arch=x86_64
# repo=eln-resilientstorage-debug-1&arch=ppc64le
# repo=eln-resilientstorage-debug-1&arch=s390x
# repo=eln-resilientstorage-debug-1&arch=x86_64
# repo=eln-resilientstorage-source-1&arch=source
```

/cc @sgallagher

**Comment by adrianreber** [comment]
Not saying we will not do it, but so far we never removed unused repositories from MirrorManager. Any reason why it has to be removed or is it just to clean it up?

**Comment by yselkowitz** [comment]
This particular variant has been discontinued and therefore the content is no longer being updated even though the rest of ELN continues on.  At a minimum, there is no more reason for mirrors to include it.  If the repos shouldn't be disabled, is there a way to avoid mirrors from including it (e.g. remove it from an rsync module)?

**Comment by adrianreber** [comment]
On the mirrormanager side we do not control or change the content at all. We just scan the primary mirror. If files or directories need to be removed it is not something the mirrormanager side can do. MirrorManager only has read-only access to all content. @nirik who is the right contact person?

**Comment by yselkowitz** [comment]
Is there no way to at least exclude it from future syncs?

**Comment by nirik** [comment]
If that content is no longer desired/updated/shipped... yeah, file a infra or releng ticket and we can remove it. 

I guess that wouldn't remove it from mm side thought?

**Comment by adrianreber** [comment]
The repository definition would still exist, but this is usually an interface only called by dnf based on repository files. So it doesn't sound problematic if it exists. We can always go into the database and remove it if necessary.

**Comment by yselkowitz** [comment]
Filed https://pagure.io/releng/issue/12459

**Comment by yselkowitz** [comment]
https://dl.fedoraproject.org/pub/eln/1/ResilientStorage/ has been removed by releng; it sounds like there is nothing further to be done here.
