### ISSUE TITLE
Move create fedora-install-N functionality to umdl

### ISSUE THREAD

**Issue by adrianreber** [fedora-infra/mirrormanager2#70]
As discussed in PR #58 the functionality provide by the script [mm2_create_install_repo](../blob/master/utility/mm2_create_install_repo) could be integrated into [umdl](../blob/master/utility/mm2_update-master-directory-list) and thus these repositories could be created automagically.

**Comment by pypingou** [comment]
This should be fixed in umdl2, didn't we backport it as well in umdl1?

**Comment by adrianreber** [comment]
There is something in repomap.py which returns fedora-install- but I do not think it has been ever tested in production. Looking at Fedora 23 there do not seem to be any fedora-install- repository created (yet?).

**Comment by pypingou** [comment]
I seem to remember we fixed this, didn't we?

**Comment by pypingou** [comment]
Looking at the code I think the repo will be created when ``releases/23`` is created

**Comment by adrianreber** [comment]
@nirik: Do you know if the fedora-install repos are still needed? Hasn't fedup been removed/retired?

**Comment by nirik** [comment]
They should no longer be needed for fedora 23 and beyond. :)

**Comment by pypingou** [comment]
So I guess we can close this ticket then :)
