### ISSUE TITLE
Hide certain fields for non-admins

### ISSUE THREAD

**Issue by adrianreber** [fedora-infra/mirrormanager2#71]
MM1 was not displaying all possible fields to non-admin users. At least site->admin_active and host->admin_active should not be visible and changeable as well as Peer ASNs for example. The complete list of items to hide from non-admin users has to be looked up in the MM1 source code.

**Comment by pypingou** [comment]
I have started on this but I only did the ``admin active`` fields

**Comment by pypingou** [comment]
For the ``Peer ASNs`` do you mean the ``asn`` or ``asn_clients`` field?

**Comment by adrianreber** [comment]
Neither, further down are different options like *Site-local Netblocks* and also *Peer ASNs* in the host view. *Peer ASNs* should only be added by admins. As well as *Site-local Netblocks* with a netmask larger than /16.

**Comment by pypingou** [comment]
By admins, you mean mirrormanager admins or the admins of the site/host ?

**Comment by adrianreber** [comment]
mirrormanager admins

**Comment by pypingou** [comment]
We can easily hide the whole 'Site-local Netblocks' but hiding it for some netmasks might end-up being tricky.
Imagine a mirror admin makes a typo and replaces a /10 netmask with /16, they won't be able to fix the typo.

**Comment by adrianreber** [comment]
Comparing it again to MM1. This is how MM1 did this:

https://git.fedorahosted.org/cgit/mirrormanager/tree/server/mirrormanager/controllers.py#n646

**Comment by adrianreber** [comment]
MM1 has been moved to pagure

https://pagure.io/mirrormanager/blob/master/f/server/mirrormanager/controllers.py#_655

**Comment by adrianreber** [comment]
PR #79 was partially solving this issue

**Comment by adrianreber** [comment]
Should all be fixed now.
