### ISSUE TITLE
Add possibility to filter mirrorlist by product

### ISSUE THREAD

**Issue by adrianreber** [fedora-infra/mirrormanager2#75]
MM1 had the ability to filter the mirrors by product. It was possible to show all EPEL mirrors regardless of version and/or architecture. MM2 has this possibility not. This breaks some external links.

http://mirrors.fedoraproject.org/publiclist/EPEL/

http://mirrors.fedoraproject.org/publiclist/Fedora/

**Comment by pypingou** [comment]
So this is now fixed in git
