### ISSUE TITLE
Introduce timeout check during run_rsync()

### ISSUE THREAD

**Issue by adrianreber** [fedora-infra/mirrormanager2#77]
Currently the crawler timeout is ignored if crawling via rsync. The possibility to specify a rsync timeout value on the command-line exists and is used but the rsync timeout options has another meaning:

```
 --timeout=TIMEOUT
              This option allows you to set a maximum I/O timeout in seconds.
              If no data is transferred for the specified time then rsync will exit.
              The default is 0, which means no timeout.
```

The crawling, however, should stop with an error if it did not finish during the specified timeout like it does with HTTP or FTP.

See #53 and #55

**Comment by pypingou** [comment]
This sound familiar as well, didn't you work on this? (or was it only for non-rsync method?)

**Comment by adrianreber** [comment]
It was only for non-rsync methods. Right now the rsync binary is spawned but we have no control how long it will run. I have not really looked into it how a timeout could be controlled. Starting a thread for it sounds a bit like overkill but I do not know if there is another option to control the duration of a spawned binary.
