### ISSUE TITLE
Provide a URL to check for basic functionality

### ISSUE THREAD

**Issue by adrianreber** [fedora-infra/mirrormanager2#83]
In environments where MM2 is running behind proxies it would be good to provide a URL which makes a simple DB connection and then returns. The MM2 start page (as opposed to the MM1 start page) does a relatively complex database query which can lead to a high memory and CPU consumption just by multiple proxies checking the availability.

There was the proposal to provide a URL like ```/ping``` which does exactly this and which then just returns OK.

**Comment by pypingou** [comment]
I'm thinking maybe more something like ``/api/repositories`` list each repo by name or something like this, something querying the DB but not too hard and still be somewhat useful
