### ISSUE TITLE
Confirm that the mirror manager badge still works with mm2

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/mirrormanager2#89]
There's a badge for being a mirror admin awarded by [this script](http://infrastructure.fedoraproject.org/infra/ansible/roles/badges/backend/files/cron/award-mirror-badge).  We should confirm that it still works against mm2 and if not, then fix it.

**Comment by pypingou** [comment]
I can already tell that currently does not work, but it's fixable :)

**Comment by ralphbean** [comment]
Cool - if it's easier to modify the script than to modify mm2, either is fine by me.

**Comment by pypingou** [comment]
Both will need to be adjusted but I already start on the MM2 side :)

**Comment by pypingou** [comment]
Ok so now we need to adjust the script :)
