### ISSUE TITLE
Make umdl logging better

### ISSUE THREAD

**Issue by nirik** [fedora-infra/mirrormanager2#98]
Right now, umdl spits out: 

06/22/2015 05:00:03 AM Starting umdl
06/22/2015 05:00:03 AM  has changed: 1434873263 != 1434948558
06/22/2015 05:02:46 AM atomic/21 has changed: 1434836123 != 1434947584
06/22/2015 05:02:47 AM atomic/21/objects/01 has changed: 1434806893 != 1434947584
...
06/22/2015 05:08:54 AM development/rawhide/armhfp/os/Packages/k has changed: 1434720949 != 1434949693
06/22/2015 05:08:56 AM development/rawhide/armhfp/os/Packages/l has changed: 1434720949 != 1434949712
06/22/2015 05:36:26 AM %s: directory already has a repository
06/22/2015 05:36:26 AM %s: directory already has a repository
06/22/2015 10:46:16 AM Ending umdl

But it says "has changed" for every directory and it's not very useful. 

It would be nice if we could add: 
- Anytime it commits to the db to update something say that in the log and what it updated. This would allow us to know when regenerating the pkl would update metalinks.
- Perhaps some kind of checkpoint thing, so it logs every 15min what it's doing. Right now there's many hour sections of the logs where it's not clear what it's doing at all. 
- Weed out these useless 'has changed' for directories that always change.

**Comment by adrianreber** [comment]
Concerning the 'has changed': I think I figured this out. To improve performance the ctime is not directly read from the database but from a dict() which is filled at the start of umdl. It is created for all categories and the keys clash if all categories are used. The examples you specified in this issue are directories which have actually changed but 'updates/16' for examples is also always listed as 'has changed'. The key 'updates/16' exists in 'Fedora Linux' and 'Fedora Secondary' and therefore umdl always thinks it has changed. This should be fixable.

**Comment by adrianreber** [comment]
Closing as it is kind of fixed with the new fullfiletimelist-* based umdl.
