### ISSUE TITLE
Drop ftp:// urls from metalinks

### ISSUE THREAD

**Issue by nirik** [fedora-infra/mirrormanager2#99]
ftp causes issues with many firewalls and is in general a horrible protocol. We should stop offerering them in metalink urls. 

We might want to check/contact any mirrors that have _only_ ftp urls and ask them to fix it or update to add a http{s} url.

**Comment by adrianreber** [comment]
I had a look at the URLs in the database. From all mirrors there are 37 (total 2009) categories with FTP only links:

      1 ftp-redirect
      1 http-forbidden (403)
      4 private
      5 no-dns
      7 http-works
      8 http-not-found (404)
     11 no-http

So this looks like we could disable FTP in mirrormanager. I will provide a patch which will prevent that FTP URLs are added in the future. Then we can remove the existing FTP URLs from the database.

**Comment by pypingou** [comment]
@adrianreber do we want to make this configurable is other system want to support ftp?

**Comment by adrianreber** [comment]
@pypingou good point. Other MM users might want to use FTP.

**Comment by adrianreber** [comment]
https://infrastructure.fedoraproject.org/cgit/ansible.git/commit/?id=59c954e8ffeb4dc4fce77d278849c645d199022a

**Comment by nirik** [comment]
Whats the status here? can we drop these yet?

**Comment by adrianreber** [comment]
We probably could. New mirrors can only be added without FTP URLs and there has not been any negative feedback until now. When I am looking at mirrors with problems I am manually deleting FTP URLs when I see them. It would be nice to remove those URLs all at once, but I see right now no problem removing them slowly for now. If anybody wants to remove all the FTP URLs right now, there are no objections from me.

**Comment by nirik** [comment]
So, we just need to go into the db and remove all the ftp containing items?

I'm for doing this sooner rather than later. I get a pretty constant stream of people asking me why we have ftp:// urls and when they are going to go away. 

@pypingou any thoughts?

**Comment by mdomsch** [comment]
FYI, the crawler crawls via rsync if available, falling back to FTP if
available, and finally http, priority being the fastest and least intrusive
way of getting the list of files.  Removing FTP will slow down the crawler
for any mirror that doesn't offer rsync but has offered FTP.

**Comment by adrianreber** [comment]
Unfortunately that (RSYNC > FTP > HTTP) is not true for quite some time now already (I thinkl). Even MirrorManager1 preferred HTTP over FTP according to

https://git.fedorahosted.org/cgit/mirrormanager.git/tree/server/crawler_perhost#n393

But then there is also the logic to first crawl per category (RSYNC), per directory (FTP) and then per file (HTTP). So there is still the possibility that mirrors are crawled using FTP but I haven't seen it very often. I think that in cases where we need too much time to crawl RSYNC is the only sane option. Especially as the crawlers seem to be behind some kind of NAT using FTP to crawl might become (or already is) problematic.

**Comment by adrianreber** [comment]
Debian is also planning to remove FTP mirrors:

https://lists.debian.org/debian-mirrors/2016/04/msg00000.html

**Comment by adrianreber** [comment]
All FTP URLs have been removed from Fedora's MirrorManager DB. Adding new FTP URLs to the DB is no longer possible. See commit above.
